SportShop-Program/Controllers/GearController.cs
using SportShop_Program.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportShop_Program.Controllers
{
    public class GearController : Controller
    {
        SportShopContextDataContext dataContext = new SportShopContextDataContext();
        // GET: Gear
        public ActionResult Index()
        {
            List<Gear> gearList = dataContext.Gears.ToList();
            return View(gearList);
        }

        public ActionResult GetBBgear()
        {
            List<Gear> bbList = dataContext.Gears.Where(item => item.SportType == "Basketball").ToList();
            return View(bbList);
        }

        public ActionResult GetFBgear()
        {
            List<Gear> fbList = dataContext.Gears.Where(item => item.SportType == "Football").ToList();
            return View(fbList);
        }

        public ActionResult GetPSGgear()
        {
            List<Gear> psgGear = dataContext.Gears.Where(item => item.TeamId == 1).ToList();
            return View(psgGear);
        }

        public ActionResult GetRMgear()
        {
            List<Gear> rmGear = dataContext.Gears.Where(item => item.TeamId == 6).ToList();
            return View(rmGear);
        }

         

        public ActionResult GetHighToLowMain()
        {
            List<Gear> gearList = dataContext.Gears.OrderByDescending(gear => gear.Price).ToList();
            return View(gearList);
        }

        public ActionResult GetLowToHighMain()
        {
            List<Gear> gearList = dataContext.Gears.OrderBy(gear => gear.Price).ToList();
            return View(gearList);
        }

        
        public ActionResult GetHighToLowBB()
        {
            List<Gear> bbList = dataContext.Gears.Where(item => item.SportType == "Basketball").OrderByDescending(gear => gear.Price).ToList();
            return View(bbList);
        }

        public ActionResult GetLowToHighBB()
        {
            List<Gear> bbList = dataContext.Gears.Where(item => item.SportType == "Basketball").OrderBy(gear => gear.Price).ToList();
            return View(bbList);
        }

        public ActionResult GetHighToLowFB()
        {
            List<Gear> fbList = dataContext.Gears.Where(item => item.SportType == "Football").OrderByDescending(gear => gear.Price).ToList();
            return View(fbList);
        }

        public ActionResult GetLowToHighFB()
        {
            List<Gear> fbList = dataContext.Gears.Where(item => item.SportType == "Football").OrderBy(gear => gear.Price).ToList();
            return View(fbList);
        }

        

        public ActionResult GetHighToLowPSG()
        {
            List<Gear> psgList = dataContext.Gears.Where(item => item.TeamId == 1).OrderByDescending(gear => gear.Price).ToList();
            return View(psgList);
        }

        public ActionResult GetLowToHighPSG()
        {
            List<Gear> psgList = dataContext.Gears.Where(item => item.TeamId == 1).OrderBy(gear => gear.Price).ToList();
            return View(psgList);
        }

        

        public ActionResult GetHighToLowRM()
        {
            List<Gear> rmList = dataContext.Gears.Where(item => item.TeamId == 6).OrderByDescending(gear => gear.Price).ToList();
            return View(rmList);
        }

        public ActionResult GetLowToHighRM()
        {
            List<Gear> rmList = dataContext.Gears.Where(item => item.TeamId == 6).OrderBy(gear => gear.Price).ToList();
            return View(rmList);
        }

        //todo 

        public ActionResult GetAdminView()
        {
            List<Gear> gearListAdmin = dataContext.Gears.ToList();
            return View(gearListAdmin);
        }


        public ActionResult GetOnlyBBAdmin()
        {
            List<Gear> bbListAdmin = dataContext.Gears.Where(item => item.SportType == "Basketball").ToList();
            return View(bbListAdmin);
        }

        public ActionResult GetOnlyFBAdmin()
        {
            List<Gear> fbListAdmin = dataContext.Gears.Where(item => item.SportType == "Football").ToList();
            return View(fbListAdmin);
        }


        public ActionResult GetPriceHighToLowMainAdmin()
        {
            List<Gear> gearListAdmin = dataContext.Gears.OrderByDescending(item => item.Price).ToList();
            return View(gearListAdmin);
        }

        public ActionResult GetPriceLowToHighMainAdmin()
        {
            List<Gear> gearListAdmin = dataContext.Gears.OrderBy(item => item.Price).ToList();
            return View(gearListAdmin);
        }


        public ActionResult GetPriceHighToLowBBAdmin()
        {
            List<Gear> bbListAdmin = dataContext.Gears.Where(item => item.SportType == "Basketball").OrderByDescending(gear => gear.Price).ToList();
            return View(bbListAdmin);
        }

        public ActionResult GetPriceLowToHighBBAdmin()
        {
            List<Gear> bbListAdmin = dataContext.Gears.Where(item => item.SportType == "Basketball").OrderBy(gear => gear.Price).ToList();
            return View(bbListAdmin);
        }


        public ActionResult GetPriceHighToLowFBAdmin()
        {
            List<Gear> fbListAdmin = dataContext.Gears.Where(item => item.SportType == "Football").OrderByDescending(gear => gear.Price).ToList();
            return View(fbListAdmin);
        }

        public ActionResult GetPriceLowToHighFBAdmin()
        {
            List<Gear> fbListAdmin = dataContext.Gears.Where(item => item.SportType == "Football").OrderBy(gear => gear.Price).ToList();
            return View(fbListAdmin);
        }

    }
}

SportShop-Program/Views/Gear/GetFBgear.cshtml
@{
    ViewBag.Title = "GetFBgear";
}

<div id="buttonsContainer">
    <h1 onclick="location.href='@Url.Action("Index", "Gear")'">Gear - Football</h1>
    <div id="mainButtons">
        | <button class="buttonItem" onclick="location.href='@Url.Action("GetAdminView", "Gear")'">Admin View</button> |
    </div>
</div>

<hr id="headerLine" />

<div class="miniSideNav">
    <h3>Present</h3><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("Index", "Gear")'">All</button><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetBBgear", "Gear")'">Basketball</button><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetFBgear", "Gear")'">Football</button><br />
    <h3>Teams</h3><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetPSGgear", "Gear")'">Paris Saint-Germain</button><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetRMgear", "Gear")'">Real Madrid</button><br />
    <h3>Sort</h3><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetHighToLowFB", "Gear")'">High-Low</button><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetLowToHighFB", "Gear")'">Low-High</button><br />
</div>
<div id="gearContainer">
    @foreach (var gear in Model)
    {
        <div class="gearCard">
            <img src="@gear.ImgLink" alt="Gear Img" />
            <h4>@gear.Brand - @gear.ProductName</h4>
            <hr />
            <p>₪@gear.Price</p>
        </div>
    }
</div>

SportShop-Program/Views/Gear/GetHighToLowFB.cshtml
@{
    ViewBag.Title = "GetHighToLowFB";
}

<div id="buttonsContainer">
    <h1 onclick="location.href='@Url.Action("Index", "Gear")'">Gear - Football</h1>
    <div id="mainButtons">
        | <button class="buttonItem" onclick="location.href='@Url.Action("GetAdminView", "Gear")'">Admin View</button> |
    </div>
</div>

<hr id="headerLine" />

<div class="miniSideNav">
    <h3>Present</h3><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("Index", "Gear")'">All</button><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetBBgear", "Gear")'">Basketball</button><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetFBgear", "Gear")'">Football</button><br />
    <h3>Teams</h3><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetPSGgear", "Gear")'">Paris Saint-Germain</button><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetRMgear", "Gear")'">Real Madrid</button><br />
    <h3>Sort</h3><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetHighToLowFB", "Gear")'">High-Low</button><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetLowToHighFB", "Gear")'">Low-High</button><br />
</div>
<div id="gearContainer">
    @foreach (var gear in Model)
    {
        <div class="gearCard">
            <img src="@gear.ImgLink" alt="Gear Img" />
            <h4>@gear.Brand - @gear.ProductName</h4>
            <hr />
            <p>₪@gear.Price</p>
        </div>
    }
</div>

SportShop-Program/Views/Gear/GetHighToLowMain.cshtml
@{
    ViewBag.Title = "GetHighToLowMain";
}

<div id="buttonsContainer">
    <h1 onclick="location.href='@Url.Action("Index", "Gear")'">Gear</h1>
    <div id="mainButtons">
        | <button class="buttonItem" onclick="location.href='@Url.Action("GetAdminView", "Gear")'">Admin View</button> |
    </div>
</div>

<hr id="headerLine" />

<div class="miniSideNav">
    <h3>Present</h3><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("Index", "Gear")'">All</button><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetBBgear", "Gear")'">Basketball</button><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetFBgear", "Gear")'">Football</button><br />
    <h3>Teams</h3><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetPSGgear", "Gear")'">Paris Saint-Germain</button><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetRMgear", "Gear")'">Real Madrid</button><br />
    <h3>Sort</h3><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetHighToLowMain", "Gear")'">High-Low</button><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetLowToHighMain", "Gear")'">Low-High</button><br />
</div>
<div id="gearContainer">
    @foreach (var gear in Model)
    {
        <div class="gearCard">
            <img src="@gear.ImgLink" alt="Gear Img" />
            <h4>@gear.Brand - @gear.ProductName</h4>
            <hr />
            <p>₪@gear.Price</p>
        </div>
    }
</div>

SportShop-Program/Views/Gear/GetHighToLowPSG.cshtml
@{
    ViewBag.Title = "GetHighToLowPSG";
}

<div id="buttonsContainer">
    <h1 onclick="location.href='@Url.Action("Index", "Gear")'">Gear - Paris Saint-Germain</h1>
    <div id="mainButtons">
        | <button class="buttonItem" onclick="location.href='@Url.Action("GetAdminView", "Gear")'">Admin View</button> |
    </div>
</div>

<hr id="headerLine" />
<div class="contentContainer">
    <div class="miniSideNav">
        <h3>Present</h3><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("Index", "Gear")'">All</button><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetBBgear", "Gear")'">Basketball</button><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetFBgear", "Gear")'">Football</button><br />
        <h3>Teams</h3><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetPSGgear", "Gear")'">Paris Saint-Germain</button><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetRMgear", "Gear")'">Real Madrid</button><br />
        <h3>Sort</h3><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetHighToLowPSG", "Gear")'">High-Low</button><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetLowToHighPSG", "Gear")'">Low-High</button><br />
    </div>
    <div id="gearContainer">
        @foreach (var gear in Model)
        {
            <div class="gearCard">
                <img src="@gear.ImgLink" alt="Gear Img" />
                <h4>@gear.Brand - @gear.ProductName</h4>
                <hr />
                <p>₪@gear.Price</p>
            </div>
        }
    </div>
</div>

SportShop-Program/Views/Gear/GetHighToLowRM.cshtml
@{
    ViewBag.Title = "GetHighToLowRM";
}

<div id="buttonsContainer">
    <h1 onclick="location.href='@Url.Action("Index", "Gear")'">Gear - Real Madrid</h1>
    <div id="mainButtons">
        | <button class="buttonItem" onclick="location.href='@Url.Action("GetAdminView", "Gear")'">Admin View</button> |
    </div>
</div>

<hr id="headerLine" />
<div class="contentContainer">
    <div class="miniSideNav">
        <h3>Present</h3><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("Index", "Gear")'">All</button><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetBBgear", "Gear")'">Basketball</button><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetFBgear", "Gear")'">Football</button><br />
        <h3>Teams</h3><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetPSGgear", "Gear")'">Paris Saint-Germain</button><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetRMgear", "Gear")'">Real Madrid</button><br />
        <h3>Sort</h3><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetHighToLowRM", "Gear")'">High-Low</button><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetLowToHighRM", "Gear")'">Low-High</button><br />
    </div>
    <div id="gearContainer">
        @foreach (var gear in Model)
        {
            <div class="gearCard">
                <img src="@gear.ImgLink" alt="Gear Img" />
                <h4>@gear.Brand - @gear.ProductName</h4>
                <hr />
                <p>₪@gear.Price</p>
            </div>
        }
    </div>
</div>

SportShop-Program/Views/Gear/GetLowToHighFB.cshtml
@{
    ViewBag.Title = "GetLowToHighFB";
}

<div id="buttonsContainer">
    <h1 onclick="location.href='@Url.Action("Index", "Gear")'">Gear - Football</h1>
    <div id="mainButtons">
        | <button class="buttonItem" onclick="location.href='@Url.Action("GetAdminView", "Gear")'">Admin View</button> |
    </div>
</div>

<hr id="headerLine" />

<div class="miniSideNav">
    <h3>Present</h3><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("Index", "Gear")'">All</button><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetBBgear", "Gear")'">Basketball</button><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetFBgear", "Gear")'">Football</button><br />
    <h3>Teams</h3><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetPSGgear", "Gear")'">Paris Saint-Germain</button><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetRMgear", "Gear")'">Real Madrid</button><br />
    <h3>Sort</h3><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetHighToLowFB", "Gear")'">High-Low</button><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetLowToHighFB", "Gear")'">Low-High</button><br />
</div>
<div id="gearContainer">
    @foreach (var gear in Model)
    {
        <div class="gearCard">
            <img src="@gear.ImgLink" alt="Gear Img" />
            <h4>@gear.Brand - @gear.ProductName</h4>
            <hr />
            <p>₪@gear.Price</p>
        </div>
    }
</div>

SportShop-Program/Views/Gear/GetLowToHighMain.cshtml
@{
    ViewBag.Title = "GetLowToHighMain";
}

<div id="buttonsContainer">
    <h1 onclick="location.href='@Url.Action("Index", "Gear")'">Gear</h1>
    <div id="mainButtons">
        | <button class="buttonItem" onclick="location.href='@Url.Action("GetAdminView", "Gear")'">Admin View</button> |
    </div>
</div>

<hr id="headerLine" />

<div class="miniSideNav">
    <h3>Present</h3><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("Index", "Gear")'">All</button><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetBBgear", "Gear")'">Basketball</button><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetFBgear", "Gear")'">Football</button><br />
    <h3>Teams</h3><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetPSGgear", "Gear")'">Paris Saint-Germain</button><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetRMgear", "Gear")'">Real Madrid</button><br />
    <h3>Sort</h3><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetHighToLowMain", "Gear")'">High-Low</button><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetLowToHighMain", "Gear")'">Low-High</button><br />
</div>
<div id="gearContainer">
    @foreach (var gear in Model)
    {
        <div class="gearCard">
            <img src="@gear.ImgLink" alt="Gear Img" />
            <h4>@gear.Brand - @gear.ProductName</h4>
            <hr />
            <p>₪@gear.Price</p>
        </div>
    }
</div>

SportShop-Program/Views/Gear/GetLowToHighPSG.cshtml
@{
    ViewBag.Title = "GetLowToHighPSG";
}

<div id="buttonsContainer">
    <h1 onclick="location.href='@Url.Action("Index", "Gear")'">Gear - Paris Saint-Germain</h1>
    <div id="mainButtons">
        | <button class="buttonItem" onclick="location.href='@Url.Action("GetAdminView", "Gear")'">Admin View</button> |
    </div>
</div>

<hr id="headerLine" />
<div class="contentContainer">
    <div class="miniSideNav">
        <h3>Present</h3><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("Index", "Gear")'">All</button><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetBBgear", "Gear")'">Basketball</button><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetFBgear", "Gear")'">Football</button><br />
        <h3>Teams</h3><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetPSGgear", "Gear")'">Paris Saint-Germain</button><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetRMgear", "Gear")'">Real Madrid</button><br />
        <h3>Sort</h3><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetHighToLowPSG", "Gear")'">High-Low</button><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetLowToHighPSG", "Gear")'">Low-High</button><br />
    </div>
    <div id="gearContainer">
        @foreach (var gear in Model)
        {
            <div class="gearCard">
                <img src="@gear.ImgLink" alt="Gear Img" />
                <h4>@gear.Brand - @gear.ProductName</h4>
                <hr />
                <p>₪@gear.Price</p>
            </div>
        }
    </div>
</div>

SportShop-Program/Views/Gear/GetLowToHighRM.cshtml
@{
    ViewBag.Title = "GetLowToHighRM";
}

<div id="buttonsContainer">
    <h1 onclick="location.href='@Url.Action("Index", "Gear")'">Gear - Real Madrid</h1>
    <div id="mainButtons">
        | <button class="buttonItem" onclick="location.href='@Url.Action("GetAdminView", "Gear")'">Admin View</button> |
    </div>
</div>

<hr id="headerLine" />
<div class="contentContainer">
    <div class="miniSideNav">
        <h3>Present</h3><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("Index", "Gear")'">All</button><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetBBgear", "Gear")'">Basketball</button><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetFBgear", "Gear")'">Football</button><br />
        <h3>Teams</h3><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetPSGgear", "Gear")'">Paris Saint-Germain</button><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetRMgear", "Gear")'">Real Madrid</button><br />
        <h3>Sort</h3><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetHighToLowRM", "Gear")'">High-Low</button><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetLowToHighRM", "Gear")'">Low-High</button><br />
    </div>
    <div id="gearContainer">
        @foreach (var gear in Model)
        {
            <div class="gearCard">
                <img src="@gear.ImgLink" alt="Gear Img" />
                <h4>@gear.Brand - @gear.ProductName</h4>
                <hr />
                <p>₪@gear.Price</p>
            </div>
        }
    </div>
</div>

SportShop-Program/Views/Gear/GetPSGgear.cshtml
@{
    ViewBag.Title = "GetPSGgear";
}

<div id="buttonsContainer">
    <h1 onclick="location.href='@Url.Action("Index", "Gear")'">Gear - Paris Saint-Germain</h1>
    <div id="mainButtons">
        | <button class="buttonItem" onclick="location.href='@Url.Action("GetAdminView", "Gear")'">Admin View</button> |
    </div>
</div>

<hr id="headerLine" />
<div class="contentContainer">
    <div class="miniSideNav">
        <h3>Present</h3><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("Index", "Gear")'">All</button><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetBBgear", "Gear")'">Basketball</button><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetFBgear", "Gear")'">Football</button><br />
        <h3>Teams</h3><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetPSGgear", "Gear")'">Paris Saint-Germain</button><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetRMgear", "Gear")'">Real Madrid</button><br />
        <h3>Sort</h3><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetHighToLowPSG", "Gear")'">High-Low</button><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetLowToHighPSG", "Gear")'">Low-High</button><br />
    </div>
    <div id="gearContainer">
        @foreach (var gear in Model)
        {
            <div class="gearCard">
                <img src="@gear.ImgLink" alt="Gear Img" />
                <h4>@gear.Brand - @gear.ProductName</h4>
                <hr />
                <p>₪@gear.Price</p>
            </div>
        }
    </div>
</div>

SportShop-Program/Views/Gear/GetPriceHighToLowFBAdmin.cshtml
@{
    ViewBag.Title = "GetPriceHighToLowFBAdmin";
}

<div id="buttonsContainer">
    <h1 onclick="location.href='@Url.Action("Index", "Gear")'">Gear - Admin View</h1>
    <div id="mainButtons">
        |  <button class="buttonItem" onclick="location.href='@Url.Action("GetAdminView", "Pants")'">Admin View</button> |
    </div>
</div>

<hr id="headerLine" />

<div class="miniSideNavAdmin">
    <button class="buttonItem" onclick="location.href='@Url.Action("GetAdminView", "Gear")'">All</button>
    <button class="buttonItem" onclick="location.href='@Url.Action("GetOnlyBBAdmin", "Gear")'">Basketball</button>
    <button class="buttonItem" onclick="location.href='@Url.Action("GetOnlyFBAdmin", "Gear")'">Football</button> |
    <button class="buttonItem" onclick="location.href='@Url.Action("GetPriceHighToLowFBAdmin", "Gear")'">High-Low</button>
    <button class="buttonItem" onclick="location.href='@Url.Action("GetPriceLowToHighFBAdmin", "Gear")'">Low-High</button>
</div>
<div id="tableContainer">
    <table id="dataTable">
        <thead>
            <tr>
                <td class="tableCell">ID</td>
                <td class="tableCell">SportType</td>
                <td class="tableCell">ProductName</td>
                <td class="tableCell">Brand</td>
                <td class="tableCell">Price</td>
                <td class="tableCell">Quantity</td>
                <td class="tableCell">TeamId</td>
                <td class="tableCell">ImgLink</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var gear in Model)
            {
                <tr>
                    <td class="tableCell">@gear.Id</td>
                    <td class="tableCell">@gear.SportType</td>
                    <td class="tableCell">@gear.ProductName</td>
                    <td class="tableCell">@gear.Brand</td>
                    <td class="tableCell">@gear.Price</td>
                    <td class="tableCell">@gear.Quantity</td>
                    <td class="tableCell">@gear.TeamId</td>
                    <td class="tableCell">@gear.ImgLink</td>
                </tr>
            }
        </tbody>
    </table>
</div>

SportShop-Program/Views/Gear/GetPriceLowToHighBBAdmin.cshtml
@{
    ViewBag.Title = "GetPriceLowToHighBBAdmin";
}

<div id="buttonsContainer">
    <h1 onclick="location.href='@Url.Action("Index", "Gear")'">Gear - Admin View</h1>
    <div id="mainButtons">
        |  <button class="buttonItem" onclick="location.href='@Url.Action("GetAdminView", "Pants")'">Admin View</button> |
    </div>
</div>

<hr id="headerLine" />

<div class="miniSideNavAdmin">
    <button class="buttonItem" onclick="location.href='@Url.Action("GetAdminView", "Gear")'">All</button>
    <button class="buttonItem" onclick="location.href='@Url.Action("GetOnlyBBAdmin", "Gear")'">Basketball</button>
    <button class="buttonItem" onclick="location.href='@Url.Action("GetOnlyFBAdmin", "Gear")'">Football</button> |
    <button class="buttonItem" onclick="location.href='@Url.Action("GetPriceHighToLowBBAdmin", "Gear")'">High-Low</button>
    <button class="buttonItem" onclick="location.href='@Url.Action("GetPriceLowToHighBBAdmin", "Gear")'">Low-High</button>
</div>
<div id="tableContainer">
    <table id="dataTable">
        <thead>
            <tr>
                <td class="tableCell">ID</td>
                <td class="tableCell">SportType</td>
                <td class="tableCell">ProductName</td>
                <td class="tableCell">Brand</td>
                <td class="tableCell">Price</td>
                <td class="tableCell">Quantity</td>
                <td class="tableCell">TeamId</td>
                <td class="tableCell">ImgLink</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var gear in Model)
            {
                <tr>
                    <td class="tableCell">@gear.Id</td>
                    <td class="tableCell">@gear.SportType</td>
                    <td class="tableCell">@gear.ProductName</td>
                    <td class="tableCell">@gear.Brand</td>
                    <td class="tableCell">@gear.Price</td>
                    <td class="tableCell">@gear.Quantity</td>
                    <td class="tableCell">@gear.TeamId</td>
                    <td class="tableCell">@gear.ImgLink</td>
                </tr>
            }
        </tbody>
    </table>
</div>