SportShop-Program/Controllers/ShoesController.cs
using SportShop_Program.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportShop_Program.Controllers
{
    public class ShoesController : Controller
    {
        SportShopContextDataContext dataContext = new SportShopContextDataContext();
        // GET: Shoes
        public ActionResult Index()
        {
            List<Shoe> shoesList = dataContext.Shoes.ToList();
            return View(shoesList);
        }

        public ActionResult GetSales()
        {
            List<Shoe> shoesInSale = dataContext.Shoes.Where(shoe => shoe.IsInSale == true).ToList();
            return View(shoesInSale);
        }

        public ActionResult GetAdminView()
        {
            List<Shoe> shoesList = dataContext.Shoes.ToList();
            return View(shoesList);
        }

        public ActionResult GetOnlyNike()
        {
            List<Shoe> nikeShoes = dataContext.Shoes.Where(shoe => shoe.Brand == "Nike").ToList();
            return View(nikeShoes);
        }

        public ActionResult GetOnlyAdidas()
        {
            List<Shoe> adidasShoes = dataContext.Shoes.Where(shoe => shoe.Brand == "Adidas").ToList();
            return View(adidasShoes);
        }

        public ActionResult GetOnlyNB()
        {
            List<Shoe> nbShoes = dataContext.Shoes.Where(shoe => shoe.Brand == "New Balance").ToList();
            return View(nbShoes);
        }

        public ActionResult GetPriceHighToLowMain()
        {
            List<Shoe> shoesList = dataContext.Shoes.OrderByDescending(shoe => shoe.Price).ToList();
            return View(shoesList);
        }

        public ActionResult GetPriceHighToLowNike()
        {
            List<Shoe> onlyNike = dataContext.Shoes.Where(shoe => shoe.Brand == "Nike").OrderByDescending(shoe => shoe.Price).ToList();
            return View(onlyNike);
        }

        public ActionResult GetPriceHighToLowAdidas()
        {
            List<Shoe> onlyAdidas = dataContext.Shoes.Where(shoe => shoe.Brand == "Adidas").OrderByDescending(shoe => shoe.Price).ToList();
            return View(onlyAdidas);
        }

        public ActionResult GetPriceHighToLowNB()
        {
            List<Shoe> onlyNB = dataContext.Shoes.Where(shoe => shoe.Brand == "New Balance").OrderByDescending(shoe => shoe.Price).ToList();
            return View(onlyNB);
        }

        public ActionResult GetPriceLowToHighMain()
        {
            List<Shoe> shoesList = dataContext.Shoes.OrderBy(shoe => shoe.Price).ToList();
            return View(shoesList);
        }

        public ActionResult GetPriceLowToHighNike()
        {
            List<Shoe> onlyNike = dataContext.Shoes.Where(shoe => shoe.Brand == "Nike").OrderBy(shoe => shoe.Price).ToList();
            return View(onlyNike);
        }

        public ActionResult GetPriceLowToHighAdidas()
        {
            List<Shoe> onlyAdidas = dataContext.Shoes.Where(shoe => shoe.Brand == "Adidas").OrderBy(shoe => shoe.Price).ToList();
            return View(onlyAdidas);
        }

        public ActionResult GetPriceLowToHighNB()
        {
            List<Shoe> onlyNB = dataContext.Shoes.Where(shoe => shoe.Brand == "New Balance").OrderBy(shoe => shoe.Price).ToList();
            return View(onlyNB);
        }







        public ActionResult GetOnlyNikeSales()
        {
            List<Shoe> nikeShoes = dataContext.Shoes.Where(shoe => shoe.Brand == "Nike" && shoe.IsInSale == true).ToList();
            return View(nikeShoes);
        }

        public ActionResult GetOnlyAdidasSales()
        {
            List<Shoe> adidasShoes = dataContext.Shoes.Where(shoe => shoe.Brand == "Adidas" && shoe.IsInSale == true).ToList();
            return View(adidasShoes);
        }

        public ActionResult GetOnlyNBSales()
        {
            List<Shoe> nbShoes = dataContext.Shoes.Where(shoe => shoe.Brand == "New Balance" && shoe.IsInSale == true).ToList();
            return View(nbShoes);
        }

        public ActionResult GetPriceHighToLowMainSales()
        {
            List<Shoe> shoesList = dataContext.Shoes.Where(shoe => shoe.IsInSale == true).OrderByDescending(shoe => shoe.Price).ToList();
            return View(shoesList);
        }

        public ActionResult GetPriceHighToLowNikeSales()
        {
            List<Shoe> onlyNike = dataContext.Shoes.Where(shoe => shoe.Brand == "Nike" && shoe.IsInSale == true).OrderByDescending(shoe => shoe.Price).ToList();
            return View(onlyNike);
        }

        public ActionResult GetPriceHighToLowAdidasSales()
        {
            List<Shoe> onlyAdidas = dataContext.Shoes.Where(shoe => shoe.Brand == "Adidas" && shoe.IsInSale == true).OrderByDescending(shoe => shoe.Price).ToList();
            return View(onlyAdidas);
        }

        public ActionResult GetPriceHighToLowNBSales()
        {
            List<Shoe> onlyNB = dataContext.Shoes.Where(shoe => shoe.Brand == "New Balance" && shoe.IsInSale == true).OrderByDescending(shoe => shoe.Price).ToList();
            return View(onlyNB);
        }

        public ActionResult GetPriceLowToHighMainSales()
        {
            List<Shoe> shoesList = dataContext.Shoes.Where(shoe => shoe.IsInSale == true).OrderBy(shoe => shoe.Price).ToList();
            return View(shoesList);
        }

        public ActionResult GetPriceLowToHighNikeSales()
        {
            List<Shoe> onlyNike = dataContext.Shoes.Where(shoe => shoe.Brand == "Nike" && shoe.IsInSale == true).OrderBy(shoe => shoe.Price).ToList();
            return View(onlyNike);
        }

        public ActionResult GetPriceLowToHighAdidasSales()
        {
            List<Shoe> onlyAdidas = dataContext.Shoes.Where(shoe => shoe.Brand == "Adidas" && shoe.IsInSale == true).OrderBy(shoe => shoe.Price).ToList();
            return View(onlyAdidas);
        }

        public ActionResult GetPriceLowToHighNBSales()
        {
            List<Shoe> onlyNB = dataContext.Shoes.Where(shoe => shoe.Brand == "New Balance" && shoe.IsInSale == true).OrderBy(shoe => shoe.Price).ToList();
            return View(onlyNB);
        }








        public ActionResult GetOnlyNikeAdmin()
        {
            List<Shoe> nikeShoes = dataContext.Shoes.Where(shoe => shoe.Brand == "Nike").ToList();
            return View(nikeShoes);
        }

        public ActionResult GetOnlyAdidasAdmin()
        {
            List<Shoe> adidasShoes = dataContext.Shoes.Where(shoe => shoe.Brand == "Adidas").ToList();
            return View(adidasShoes);
        }

        public ActionResult GetOnlyNBAdmin()
        {
            List<Shoe> nbShoes = dataContext.Shoes.Where(shoe => shoe.Brand == "New Balance").ToList();
            return View(nbShoes);
        }

        public ActionResult GetPriceHighToLowMainAdmin()
        {
            List<Shoe> shoesList = dataContext.Shoes.OrderByDescending(shoe => shoe.Price).ToList();
            return View(shoesList);
        }

        public ActionResult GetPriceHighToLowNikeAdmin()
        {
            List<Shoe> onlyNike = dataContext.Shoes.Where(shoe => shoe.Brand == "Nike").OrderByDescending(shoe => shoe.Price).ToList();
            return View(onlyNike);
        }

        public ActionResult GetPriceHighToLowAdidasAdmin()
        {
            List<Shoe> onlyAdidas = dataContext.Shoes.Where(shoe => shoe.Brand == "Adidas").OrderByDescending(shoe => shoe.Price).ToList();
            return View(onlyAdidas);
        }

        public ActionResult GetPriceHighToLowNBAdmin()
        {
            List<Shoe> onlyNB = dataContext.Shoes.Where(shoe => shoe.Brand == "New Balance").OrderByDescending(shoe => shoe.Price).ToList();
            return View(onlyNB);
        }

        public ActionResult GetPriceLowToHighMainAdmin()
        {
            List<Shoe> shoesList = dataContext.Shoes.OrderBy(shoe => shoe.Price).ToList();
            return View(shoesList);
        }

        public ActionResult GetPriceLowToHighNikeAdmin()
        {
            List<Shoe> onlyNike = dataContext.Shoes.Where(shoe => shoe.Brand == "Nike").OrderBy(shoe => shoe.Price).ToList();
            return View(onlyNike);
        }

        public ActionResult GetPriceLowToHighAdidasAdmin()
        {
            List<Shoe> onlyAdidas = dataContext.Shoes.Where(shoe => shoe.Brand == "Adidas").OrderBy(shoe => shoe.Price).ToList();
            return View(onlyAdidas);
        }

        public ActionResult GetPriceLowToHighNBAdmin()
        {
            List<Shoe> onlyNB = dataContext.Shoes.Where(shoe => shoe.Brand == "New Balance").OrderBy(shoe => shoe.Price).ToList();
            return View(onlyNB);
        }

    }
}

SportShop-Program/Views/Shoes/GetOnlyAdidas.cshtml
@{
    ViewBag.Title = "GetOnlyAdidas";
}

<div id="buttonsContainer">
    <h1 onclick="location.href='@Url.Action("Index", "Shoes")'">Shoes</h1>
    <div id="mainButtons">
        <button class="buttonItem" onclick="location.href='@Url.Action("GetAdminView", "Shoes")'">Admin View</button> |
        <button class="buttonItem" onclick="location.href='@Url.Action("GetSales", "Shoes")'">Sales</button>
    </div>
</div>

<hr id="headerLine" />

<div class="miniSideNav">
    <h3>Present</h3><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("Index", "Shoes")'">All</button><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetOnlyNike", "Shoes")'">Nike</button><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetOnlyAdidas", "Shoes")'">Adidas</button><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetOnlyNB", "Shoes")'">New Balance</button><br />
    <h3>Sort</h3><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetPriceHighToLowAdidas", "Shoes")'">High-Low</button><br />
    <button class="buttonItem">Low-High</button><br />
</div>
<div id="cardsContainer">
    @foreach (var shoe in Model)
    {
        <div class="shoeCard">
            <img src="@shoe.ImgLink" alt=" Shoe Img" />
            <h4>@shoe.Brand - @shoe.ShoeModel</h4>
            <hr />
            <p>₪@shoe.Price</p>
        </div>
    }
</div>

SportShop-Program/Views/Shoes/GetOnlyAdidasSales.cshtml
@{
    ViewBag.Title = "GetOnlyAdidasSales";
}

<div id="buttonsContainer">
    <h1 onclick="location.href='@Url.Action("Index", "Shoes")'">Shoes - In Sale</h1>
    <div id="mainButtons">
        <button class="buttonItem" onclick="location.href='@Url.Action("GetAdminView", "Shoes")'">Admin View</button> |
        <button class="buttonItem" onclick="location.href='@Url.Action("GetSales", "Shoes")'">Sales</button>
    </div>
</div>

<hr id="headerLine" />
<div>
    <div class="miniSideNav">
        <h3>Present</h3><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetSales", "Shoes")'">All</button><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetOnlyNikeSales", "Shoes")'">Nike</button><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetOnlyAdidasSales", "Shoes")'">Adidas</button><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetOnlyNBSales", "Shoes")'">New Balance</button><br />
        <h3>Sort</h3><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetPriceHighToLowAdidasSales", "Shoes")'">High-Low</button><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetPriceLowToHighAdidasSales", "Shoes")'">Low-High</button><br />
    </div>
    <div id="cardsContainer">
        @foreach (var shoe in Model)
        {
            <div class="shoeCard">
                <img src="@shoe.ImgLink" alt=" Shoe Img" />
                <h4>@shoe.Brand - @shoe.ShoeModel</h4>
                <hr />
                <p>₪@shoe.Price</p>
            </div>
        }
    </div>
</div>

SportShop-Program/Views/Shoes/GetOnlyNBAdmin.cshtml
@{
    ViewBag.Title = "GetOnlyNBAdmin";
}

<div id="buttonsContainer">
    <h1 onclick="location.href='@Url.Action("Index", "Shoes")'">Shoes - Admin View</h1>
    <div id="mainButtons">
        <button class="buttonItem" onclick="location.href='@Url.Action("GetAdminView", "Shoes")'">Admin View</button> |
        <button class="buttonItem" onclick="location.href='@Url.Action("GetSales", "Shoes")'">Sales</button>
    </div>
</div>

<hr id="headerLine" />


<div class="miniSideNavAdmin">
    <button class="buttonItem" onclick="location.href='@Url.Action("GetAdminView", "Shoes")'">All</button>
    <button class="buttonItem" onclick="location.href='@Url.Action("GetOnlyNikeAdmin", "Shoes")'">Nike</button>
    <button class="buttonItem" onclick="location.href='@Url.Action("GetOnlyAdidasAdmin", "Shoes")'">Adidas</button>
    <button class="buttonItem" onclick="location.href='@Url.Action("GetOnlyNBAdmin", "Shoes")'">New Balance</button> |
    <button class="buttonItem" onclick="location.href='@Url.Action("GetPriceHighToLowNBAdmin", "Shoes")'">High-Low</button>
    <button class="buttonItem" onclick="location.href='@Url.Action("GetPriceLowToHighNBAdmin", "Shoes")'">Low-High</button>
</div>
<div id="tableContainer">
    <table id="dataTable">
        <thead>
            <tr>
                <td class="tableCell">ID</td>
                <td class="tableCell">ShoeType</td>
                <td class="tableCell">Brand</td>
                <td class="tableCell">ShoeModel</td>
                <td class="tableCell">Price</td>
                <td class="tableCell">Quantity</td>
                <td class="tableCell">IsInSale</td>
                <td class="tableCell">ImgLink</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var shoe in Model)
            {
                <tr>
                    <td class="tableCell">@shoe.Id</td>
                    <td class="tableCell">@shoe.ShoeType</td>
                    <td class="tableCell">@shoe.Brand</td>
                    <td class="tableCell">@shoe.ShoeModel</td>
                    <td class="tableCell">@shoe.Price</td>
                    <td class="tableCell">@shoe.Quantity</td>
                    <td class="tableCell">@shoe.IsInSale</td>
                    <td class="tableCell">@shoe.ImgLink</td>
                </tr>
            }
        </tbody>
    </table>
</div>

SportShop-Program/Views/Shoes/GetOnlyNike.cshtml
@{
    ViewBag.Title = "GetOnlyNike";
}

<div id="buttonsContainer">
    <h1 onclick="location.href='@Url.Action("Index", "Shoes")'">Shoes</h1>
    <div id="mainButtons">
        <button class="buttonItem" onclick="location.href='@Url.Action("GetAdminView", "Shoes")'">Admin View</button> |
        <button class="buttonItem" onclick="location.href='@Url.Action("GetSales", "Shoes")'">Sales</button>
    </div>
</div>

<hr id="headerLine" />
<div>
    <div class="miniSideNav">
        <h3>Present</h3><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("Index", "Shoes")'">All</button><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetOnlyNike", "Shoes")'">Nike</button><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetOnlyAdidas", "Shoes")'">Adidas</button><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetOnlyNB", "Shoes")'">New Balance</button><br />
        <h3>Sort</h3><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetPriceHighToLowNike", "Shoes")'">High-Low</button><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetPriceLowToHighNike", "Shoes")'">Low-High</button><br />
    </div>
    <div id="cardsContainer">
        @foreach (var shoe in Model)
        {
            <div class="shoeCard">
                <img src="@shoe.ImgLink" alt=" Shoe Img" />
                <h4>@shoe.Brand - @shoe.ShoeModel</h4>
                <hr />
                <p>₪@shoe.Price</p>
            </div>
        }
    </div>
</div>

SportShop-Program/Views/Shoes/GetOnlyNikeSales.cshtml
@{
    ViewBag.Title = "GetOnlyNikeSales";
}

<div id="buttonsContainer">
    <h1 onclick="location.href='@Url.Action("Index", "Shoes")'">Shoes - In Sale</h1>
    <div id="mainButtons">
        <button class="buttonItem" onclick="location.href='@Url.Action("GetAdminView", "Shoes")'">Admin View</button> |
        <button class="buttonItem" onclick="location.href='@Url.Action("GetSales", "Shoes")'">Sales</button>
    </div>
</div>

<hr id="headerLine" />
<div>
    <div class="miniSideNav">
        <h3>Present</h3><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetSales", "Shoes")'">All</button><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetOnlyNikeSales", "Shoes")'">Nike</button><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetOnlyAdidasSales", "Shoes")'">Adidas</button><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetOnlyNBSales", "Shoes")'">New Balance</button><br />
        <h3>Sort</h3><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetPriceHighToLowNikeSales", "Shoes")'">High-Low</button><br />
        <button class="buttonItem" onclick="location.href='@Url.Action("GetPriceLowToHighNikeSales", "Shoes")'">Low-High</button><br />
    </div>
    <div id="cardsContainer">
        @foreach (var shoe in Model)
        {
            <div class="shoeCard">
                <img src="@shoe.ImgLink" alt=" Shoe Img" />
                <h4>@shoe.Brand - @shoe.ShoeModel</h4>
                <hr />
                <p>₪@shoe.Price</p>
            </div>
        }
    </div>
</div>

SportShop-Program/Views/Shoes/GetPriceHighToLowAdidas.cshtml
@{
    ViewBag.Title = "GetPriceHighToLowAdidas";
}

<div id="buttonsContainer">
    <h1 onclick="location.href='@Url.Action("Index", "Shoes")'">Shoes</h1>
    <div id="mainButtons">
        <button class="buttonItem" onclick="location.href='@Url.Action("GetAdminView", "Shoes")'">Admin View</button> |
        <button class="buttonItem" onclick="location.href='@Url.Action("GetSales", "Shoes")'">Sales</button>
    </div>
</div>

<hr id="headerLine" />

<div class="miniSideNav">
    <h3>Present</h3><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("Index", "Shoes")'">All</button><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetOnlyNike", "Shoes")'">Nike</button><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetOnlyAdidas", "Shoes")'">Adidas</button><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetOnlyNB", "Shoes")'">New Balance</button><br />
    <h3>Sort</h3><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetPriceHighToLowAdidas", "Shoes")'">High-Low</button><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetPriceLowToHighAdidas", "Shoes")'">Low-High</button><br />
</div>
<div id="cardsContainer">
    @foreach (var shoe in Model)
    {
        <div class="shoeCard">
            <img src="@shoe.ImgLink" alt=" Shoe Img" />
            <h4>@shoe.Brand - @shoe.ShoeModel</h4>
            <hr />
            <p>₪@shoe.Price</p>
        </div>
    }
</div>

SportShop-Program/Views/Shoes/GetPriceHighToLowAdidasSales.cshtml
@{
    ViewBag.Title = "GetPriceHighToLowAdidasSales";
}

<div id="buttonsContainer">
    <h1 onclick="location.href='@Url.Action("Index", "Shoes")'">Shoes - In Sale</h1>
    <div id="mainButtons">
        <button class="buttonItem" onclick="location.href='@Url.Action("GetAdminView", "Shoes")'">Admin View</button> |
        <button class="buttonItem" onclick="location.href='@Url.Action("GetSales", "Shoes")'">Sales</button>
    </div>
</div>

<hr id="headerLine" />

<div class="miniSideNav">
    <h3>Present</h3><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetSales", "Shoes")'">All</button><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetOnlyNikeSales", "Shoes")'">Nike</button><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetOnlyAdidasSales", "Shoes")'">Adidas</button><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetOnlyNBSales", "Shoes")'">New Balance</button><br />
    <h3>Sort</h3><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetPriceHighToLowAdidasSales", "Shoes")'">High-Low</button><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetPriceLowToHighAdidasSales", "Shoes")'">Low-High</button><br />
</div>
<div id="cardsContainer">
    @foreach (var shoe in Model)
    {
        <div class="shoeCard">
            <img src="@shoe.ImgLink" alt=" Shoe Img" />
            <h4>@shoe.Brand - @shoe.ShoeModel</h4>
            <hr />
            <p>₪@shoe.Price</p>
        </div>
    }
</div>

SportShop-Program/Views/Shoes/GetPriceHighToLowNikeSales.cshtml
@{
    ViewBag.Title = "GetPriceHighToLowNikeSales";
}

<div id="buttonsContainer">
    <h1 onclick="location.href='@Url.Action("Index", "Shoes")'">Shoes - In Sale</h1>
    <div id="mainButtons">
        <button class="buttonItem" onclick="location.href='@Url.Action("GetAdminView", "Shoes")'">Admin View</button> |
        <button class="buttonItem" onclick="location.href='@Url.Action("GetSales", "Shoes")'">Sales</button>
    </div>
</div>

<hr id="headerLine" />

<div class="miniSideNav">
    <h3>Present</h3><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetSales", "Shoes")'">All</button><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetOnlyNikeSales", "Shoes")'">Nike</button><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetOnlyAdidasSales", "Shoes")'">Adidas</button><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetOnlyNBSales", "Shoes")'">New Balance</button><br />
    <h3>Sort</h3><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetPriceHighToLowNikeSales", "Shoes")'">High-Low</button><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetPriceLowToHighNikeSales", "Shoes")'">Low-High</button><br />
</div>
<div id="cardsContainer">
    @foreach (var shoe in Model)
    {
        <div class="shoeCard">
            <img src="@shoe.ImgLink" alt=" Shoe Img" />
            <h4>@shoe.Brand - @shoe.ShoeModel</h4>
            <hr />
            <p>₪@shoe.Price</p>
        </div>
    }
</div>

SportShop-Program/Views/Shoes/GetPriceLowToHighAdidasSales.cshtml
@{
    ViewBag.Title = "GetPriceLowToHighAdidasSales";
}

<div id="buttonsContainer">
    <h1 onclick="location.href='@Url.Action("Index", "Shoes")'">Shoes - In Sale</h1>
    <div id="mainButtons">
        <button class="buttonItem" onclick="location.href='@Url.Action("GetAdminView", "Shoes")'">Admin View</button> |
        <button class="buttonItem" onclick="location.href='@Url.Action("GetSales", "Shoes")'">Sales</button>
    </div>
</div>

<hr id="headerLine" />

<div class="miniSideNav">
    <h3>Present</h3><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetSales", "Shoes")'">All</button><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetOnlyNikeSales", "Shoes")'">Nike</button><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetOnlyAdidasSales", "Shoes")'">Adidas</button><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetOnlyNBSales", "Shoes")'">New Balance</button><br />
    <h3>Sort</h3><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetPriceHighToLowAdidasSales", "Shoes")'">High-Low</button><br />
    <button class="buttonItem" onclick="location.href='@Url.Action("GetPriceLowToHighAdidasSales", "Shoes")'">Low-High</button><br />
</div>
<div id="cardsContainer">
    @foreach (var shoe in Model)
    {
        <div class="shoeCard">
            <img src="@shoe.ImgLink" alt=" Shoe Img" />
            <h4>@shoe.Brand - @shoe.ShoeModel</h4>
            <hr />
            <p>₪@shoe.Price</p>
        </div>
    }
</div>

SportShop-Program/Views/Shoes/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<div id="buttonsContainer">
    <h1 onclick="location.href='@Url.Action("Index", "Shoes")'">Shoes</h1>
    <div id="mainButtons">
        <button class="buttonItem" onclick="location.href='@Url.Action("GetAdminView", "Shoes")'">Admin View</button> |
        <button class="buttonItem" onclick="location.href='@Url.Action("GetSales", "Shoes")'">Sales</button>
    </div>
</div>

<hr id="headerLine"/>
<div id="cardsContainer">
    @foreach (var shoe in Model)
    {
        <div class="shoeCard">
            <img src="@shoe.ImgLink" alt=" Shoe Img" />
            <h4>@shoe.Brand - @shoe.ShoeModel</h4>
            <hr />
            <p>₪@shoe.Price</p>
        </div>
    }
</div>